# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: qfvfq1@gmail.com
author_name: qfvfq1
contract_name: box_storage
deployment_language: python
preset_name: production
project_name: box_storage

